parameters:
#    pedidos.example.class: diateco\pedidosBundle\Example

services:
#    pedidos.example:
#        class: %pedidos.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
